import { StyleSheet } from "react-native";

import { BrandColors, FontStyles, Radius, Spacing } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: { gap: Spacing.two },
  errorBanner: {
    marginTop: Spacing.one,
    backgroundColor: BrandColors.ember + "22",
    borderWidth: 1,
    borderColor: BrandColors.ember,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  errorText: { ...FontStyles.system, fontSize: 13, color: BrandColors.ember },
  groupCard: {
    backgroundColor: BrandColors.ink,
    borderWidth: 1,
    borderColor: BrandColors.charcoal,
    borderRadius: Radius.md,
    overflow: "hidden",
  },
  groupHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: Spacing.three,
  },
  groupLabel: { flex: 1 },
  chevron: { fontSize: 12, color: BrandColors.ash, marginLeft: Spacing.two },
  groupBusyHint: { ...FontStyles.systemLight, fontSize: 11, color: BrandColors.divine },
  itemList: { paddingHorizontal: Spacing.three, paddingBottom: Spacing.three },
  groupBusyBanner: {
    gap: Spacing.one,
    marginBottom: Spacing.two,
    paddingBottom: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: BrandColors.charcoal,
  },
  groupBusyText: { ...FontStyles.bodyLightItalic, fontSize: 13, color: BrandColors.bone },
  divider: { height: 1, backgroundColor: BrandColors.charcoal, marginVertical: Spacing.two },
  itemRow: { gap: Spacing.two },
  itemInfo: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  itemBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  itemName: { flex: 1 },
  itemNameDimmed: { opacity: 0.4 },
  durationText: {
    ...FontStyles.systemLight,
    fontSize: 12,
    color: BrandColors.ash,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  disabledReason: { ...FontStyles.systemLight, fontSize: 12, color: BrandColors.ash },
  materialsColumn: { gap: 2 },
  materialText: { ...FontStyles.system, fontSize: 11, color: BrandColors.ember },
  materialTextSufficient: { color: BrandColors.hollow },
  activeStatus: { flexDirection: "row", alignItems: "center", gap: Spacing.two },
  activeLabel: {
    ...FontStyles.system,
    fontSize: 11,
    color: BrandColors.divine,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  activeTime: { ...FontStyles.systemLight, fontSize: 11, color: BrandColors.ash },
  confirmButton: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: BrandColors.hollowMuted,
  },
  confirmButtonDisabled: { borderColor: BrandColors.slate, opacity: 0.5 },
  confirmText: {
    ...FontStyles.system,
    fontSize: 12,
    color: BrandColors.hollow,
    letterSpacing: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.four,
  },
  modalContent: {
    backgroundColor: BrandColors.ink,
    borderWidth: 1,
    borderColor: BrandColors.charcoal,
    borderRadius: Radius.md,
    padding: Spacing.four,
    width: "100%",
    maxWidth: 340,
    gap: Spacing.three,
  },
  modalTitle: { textAlign: "center" },
  modalSubtitle: {
    ...FontStyles.systemLight,
    fontSize: 13,
    color: BrandColors.ash,
    textAlign: "center",
  },
  destList: { gap: Spacing.two },
  destOption: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: BrandColors.charcoal,
  },
  destOptionSelected: {
    borderColor: BrandColors.hollowMuted,
    backgroundColor: BrandColors.hollowFaint,
  },
  destOptionText: {
    ...FontStyles.system,
    fontSize: 14,
    color: BrandColors.ash,
    textTransform: "capitalize",
  },
  destOptionTextSelected: { color: BrandColors.hollow },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: Spacing.two,
    marginTop: Spacing.one,
  },
  cancelButton: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: BrandColors.charcoal,
  },
  cancelText: { ...FontStyles.system, fontSize: 12, color: BrandColors.ash, letterSpacing: 2 },
});
