"""Spec pins for the seven Steppe, Keldaran, and Sunward creatures.

Source: docs/game_mechanics/game_mechanics_bestiary.md:781-966.
"""

SPEC = {
    "steppe_razorwing": (
        "beast",
        1,
        2,
        15,
        13,
        10,
        50,
        (10, 16, 10, 3, 14, 6),
        ("DEX",),
        (
            ("Talons", "melee", 5, 5, "1d6+3", "slashing", "On hit from a dive (30+ ft descent): +1d6 damage"),
            ("Wing Slash", "melee", 5, 5, "1d4+3", "slashing", "Can target two adjacent creatures"),
        ),
        "drathian_steppe",
        ("drathian_steppe", "keldaran_mountains"),
    ),
    "steppe_bison": (
        "beast",
        1,
        2,
        28,
        11,
        40,
        50,
        (18, 8, 16, 2, 10, 4),
        ("STR", "CON"),
        (
            (
                "Gore",
                "melee",
                5,
                6,
                "2d6+4",
                "piercing",
                "If charged 20+ ft: target STR save DC 14 or knocked prone and Stunned 1 round",
            ),
        ),
        "drathian_steppe",
        ("drathian_steppe",),
    ),
    "rock_viper": (
        "beast",
        1,
        1,
        6,
        13,
        20,
        15,
        (4, 16, 10, 1, 10, 2),
        ("DEX",),
        (
            (
                "Bite",
                "melee",
                5,
                5,
                "1",
                "piercing",
                "On hit: +1d6 poison damage. DC 11 CON save or Poisoned 1 hour. Failed by 5+: Paralyzed 10 min",
            ),
        ),
        "keldaran_mountains",
        ("keldaran_mountains",),
    ),
    "cave_wyrm": (
        "beast",
        2,
        5,
        52,
        15,
        30,
        150,
        (16, 12, 16, 4, 12, 8),
        ("STR", "CON"),
        (
            ("Bite", "melee", 5, 6, "1d10+3", "piercing", "On crit: target grappled (escape DC 14)"),
            ("Tail Sweep", "melee", 10, 6, "1d8+3", "bludgeoning", "DEX save DC 14 or knocked prone. Reach 10 ft"),
            (
                "Acid Spit",
                "ranged",
                30,
                4,
                "2d6",
                "acid",
                "Recharge 5-6. DEX save DC 13 for half. Corrodes metal armor (-1 AC until repaired)",
            ),
        ),
        "keldaran_mountains",
        ("keldaran_mountains", "underground"),
    ),
    "war_golem": (
        "construct",
        3,
        10,
        100,
        18,
        25,
        500,
        (22, 6, 20, 3, 10, 1),
        ("STR", "CON"),
        (
            ("Slam", "melee", 10, 9, "2d10+6", "bludgeoning", "Target pushed 10 ft"),
            (
                "Stone Throw",
                "ranged",
                60,
                9,
                "2d8+6",
                "bludgeoning",
                "Throws chunks of itself. Each throw reduces max HP by 5 until repaired",
            ),
        ),
        "keldaran_mountains",
        ("keldaran_mountains", "underground"),
    ),
    "saltmarsh_lurker": (
        "beast",
        1,
        2,
        20,
        12,
        20,
        50,
        (14, 12, 14, 2, 10, 4),
        ("CON",),
        (
            (
                "Bite",
                "melee",
                5,
                4,
                "1d8+2",
                "piercing",
                "On hit: target grappled (escape DC 12). Grappled targets pulled underwater next turn",
            ),
            ("Tail Slap", "melee", 10, 4, "1d6+2", "bludgeoning", "Reach 10 ft"),
        ),
        "sunward_coast",
        ("sunward_coast",),
    ),
    "tidecaller_eel": (
        "beast",
        2,
        4,
        35,
        13,
        10,
        100,
        (16, 14, 14, 3, 10, 6),
        ("DEX", "CON"),
        (
            ("Bite", "melee", 10, 6, "1d10+3", "piercing", "Target grappled (escape DC 14)"),
            (
                "Lightning Discharge",
                "area",
                15,
                0,
                "2d8",
                "lightning",
                "CON save DC 13. Water only; all creatures in water within 15 ft. Recharge 5-6",
            ),
        ),
        "sunward_coast",
        ("sunward_coast",),
    ),
}

LOOT = {
    "steppe_razorwing": (
        ("razorwing_feather", "1d6", 1.0, ()),
        ("razorwing_talons", 2, 0.75, (("survival", "trained"),)),
    ),
    "steppe_bison": (
        ("bison_hide", 1, 1.0, (("survival", "trained"),)),
        ("bison_horn", 2, 1.0, ()),
        ("bison_meat", 8, 1.0, (("survival", "trained"),)),
    ),
    "rock_viper": (
        ("viper_venom", 1, 0.75, (("survival", "expert"),)),
        ("viper_skin", 1, 0.5, (("survival", "trained"),)),
    ),
    "cave_wyrm": (
        ("cave_wyrm_scales", "1d6", 1.0, (("survival", "trained"),)),
        ("wyrm_acid_gland", 1, 0.5, (("survival", "expert"),)),
        ("wyrm_teeth", "1d4", 1.0, ()),
        ("cave_gemstone", "1d4", 0.25, (("investigation", "trained"),)),
    ),
    "war_golem": (
        ("golem_core", 1, 1.0, (("crafting", "expert"),)),
        ("enchanted_stone", "2d4", 1.0, ()),
        ("forged_steel", "1d4", 0.75, (("crafting", "trained"),)),
        ("power_crystal", 1, 0.25, (("arcana", "expert"),)),
    ),
    "saltmarsh_lurker": (("lurker_hide", 1, 1.0, (("survival", "trained"),)), ("lurker_teeth", "1d4", 1.0, ())),
    "tidecaller_eel": (
        ("eel_skin", 1, 1.0, (("survival", "trained"),)),
        ("lightning_gland", 1, 0.5, (("survival", "expert"),)),
        ("eel_oil", 2, 0.75, (("survival", "trained"),)),
    ),
}

BEHAVIOR = {
    "steppe_razorwing": (
        "Dive-attacks from height. Targets small or isolated creatures. Retreats to altitude between attacks.",
        "Flees after taking any damage (unless defending nest).",
        "Pair or flock of 4-8",
        ("Drathian Steppe", "mountain passes", "open highlands"),
        ("Flyby", "Keen Sight"),
        (),
    ),
    "steppe_bison": (
        "Herd animal. Normally docile. Panics and stampedes when threatened. Individual bison charge only when cornered or defending calves.",
        "Stampedes away from danger. Individual fights to death only if cornered.",
        "Herd of 6-20 (only 1-2 fight; rest flee)",
        ("Drathian Steppe", "open grasslands"),
        ("Stampede",),
        (),
    ),
    "rock_viper": (
        "Ambush. Hides in rocks, strikes exposed ankles or hands. Does not pursue.",
        "Flees immediately after striking.",
        "Solitary or nest of 2-3",
        ("Keldaran Mountains", "mountain passes", "cave entrances"),
        ("Camouflage", "Tiny"),
        (),
    ),
    "cave_wyrm": (
        "Ambush from tunnel walls or ceiling. Uses tremorsense to detect approaching prey. Fights aggressively — cave wyrms are always hungry.",
        "Fights to 25% HP, then attempts to burrow and escape.",
        "Solitary or mated pair",
        ("Keldaran mines", "mountain caves", "underground passages"),
        ("Tremorsense", "Darkvision", "Scales"),
        (),
    ),
    "war_golem": (
        "Follows last instructions given by its creator. Most Keldaran war golems guard ancient holds or mines. They do not communicate and cannot be reasoned with. They perform their duty until destroyed.",
        "Fights to destruction. Cannot flee, surrender, or negotiate.",
        "Solitary (guarding a specific location)",
        ("Keldaran ancient holds", "deep mines", "ruins from the pre-Sundering era"),
        ("Damage Immunity", "Resistance", "Magic Resistance", "Immutable Form"),
        (),
    ),
    "saltmarsh_lurker": (
        "Lies submerged near banks or fords. Grabs creatures at the water's edge and drags them under.",
        "Releases prey if it takes 10+ damage in one hit.",
        "Solitary",
        ("Sunward Coast marshes", "river crossings", "wetlands"),
        ("Hold Breath", "Ambush from Water", "Swamp Camouflage"),
        (),
    ),
    "tidecaller_eel": (
        "Territorial in coastal waters. Uses Lightning Discharge to stun prey, then bites grappled targets.",
        "Retreats to deep water if outmatched on shore.",
        "Solitary or pair",
        ("Sunward Coast waters", "river mouths", "coastal caves"),
        ("Water Breathing", "Electricity Absorption", "Keen Vibration Sense"),
        (),
    ),
}

ABILITIES = {
    "steppe_razorwing": (
        ("Doesn't provoke opportunity attacks when flying away.", "Advantage on Perception checks by sight."),
        (),
    ),
    "steppe_bison": (
        (
            "If 3+ bison charge in the same direction, all creatures in the path: DEX save DC 14 or 2d8 bludgeoning damage and knocked prone.",
        ),
        (),
    ),
    "rock_viper": (
        ("Advantage on Stealth checks in rocky terrain.", "Can hide in cracks and crevices. Climbs 20 ft."),
        (),
    ),
    "cave_wyrm": (
        (
            "Detects movement through ground within 30 ft.",
            "Darkvision 60 ft.",
            "Resists acid damage. Climbs 30 ft and burrows 10 ft.",
        ),
        (),
    ),
    "war_golem": (
        (
            "Immune to poison and psychic damage.",
            "Resists non-magical physical damage.",
            "Advantage on saves versus spells.",
            "Immune to effects that would alter its form.",
        ),
        (),
    ),
    "saltmarsh_lurker": (
        (
            "Can hold its breath for 30 minutes. Swims 40 ft.",
            "Advantage on Stealth while submerged.",
            "Camouflages in swamp terrain.",
        ),
        (),
    ),
    "tidecaller_eel": (
        (
            "Breathes underwater. Swims 50 ft.",
            "Immune to lightning; heals HP equal to lightning damage dealt to it.",
            "Detects movement in water within 60 ft.",
        ),
        (),
    ),
}
